#!/bin/sh
#!/bin/bash

# By jhack
# http://twitter.com/_jhack
# http://github.com/jhack

# Executable that asks for an IP address, then creates a reverse VNC connection to said IP address.

remoteMachine=$remoteMachine
remoteUser=$remoteUser

clear
echo "# revvnc # \n"

echo "This will create a reverse SSH tunnel on port 5900, a common VNC port."
echo "When you are finished and want to close the tunnel, type 'exit' on the remote machine.\n"

echo "Enter remote username: \c"
read remoteUser
echo "Enter hostname or IP address of remote machine: \c"
read remoteMachine

ssh "$remoteUser"@"$remoteMachine" -R 5900:127.0.0.1:5900
